#pragma config(Sensor, S3,     back,           sensorLightActive)
#pragma config(Sensor, S4,     front,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float calibration = 50-46;
float fcali = 48;
float bcali = 52;
float kp = 0.8;
float kd = 0.1;
float ki = 0.1;
float prevpower = 0;
float threshold = 5;
task main()
{
	clearTimer(T1);
	float prevT = (float)time1[T1] / 1000;
	float preverror = 0;
	float ierror = 0;
	while(true) {
		float f = (float)SensorValue(front);
		float b = (float)SensorValue(back);
		//writeDebugStreamLine("%d, %d", f, b);

		float error = f > fcali ? f-fcali : bcali - b;
		float t = (float)time1[T1] / 1000;
		float dt = t - prevT;
		float derror = 0;
		if (dt != 0) {
			prevT = t;
			derror = (error - preverror) / dt;
		}
		ierror = ierror + derror * dt;
		int sign1 = error > 0 ? 1 : -1;
		int sign2 = derror > 0 ? 1 : -1;
		int sign3 = ierror > 0 ? 1 : -1;
		float pid = sign1 * kp * error * error + sign2 * kd * derror * derror + sign3 * ki * ierror * ierror;
		float power = pid;
		if (abs(error) <= threshold) {
			power = power * 10;
		}
		int sign = pid > 0 ? 1 : -1;
		power = abs(power) > 100 ? 80 * sign : power;
		prevpower = power;
		writeDebugStreamLine("%d\n", power);
		motor[motorB] = (int)power;
		motor[motorC] = (int)power;
		wait1Msec(5);
	}
	while(nNxtButtonPressed != kExitButton) {}
}
