#pragma config(Sensor, S3,     back,           sensorLightActive)
#pragma config(Sensor, S4,     front,          sensorLightActive)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float fcali = 69;
float bcali = 75;
float kp = 17/2;
float kd = 0.3/2;
float ki = 0.3/1.5;
task main()
{
	float preverror = 0;
	float ierror = 0;
	while(true) {
		float f = (float)SensorValue(front);
		float b = (float)SensorValue(back);

		float error = f > fcali ? f-fcali : bcali - b;
		float derror = error - preverror;
		ierror = ierror + error;
		preverror = error;

		float pid = kp * error + kd * derror + ki * ierror;
		float power = pid;
		int sign = pid > 0 ? 1 : -1;
		power = abs(power) > 100 ? 80 * sign : power; //prevent overly large power input
		motor[leftMotor] = (int)power;
		motor[rightMotor] = (int)power;
		wait1Msec(5);
	}
	while(nNxtButtonPressed != kExitButton) {}
}
