#pragma config(Sensor, S3,     back,           sensorLightActive)
#pragma config(Sensor, S4,     front,          sensorLightActive)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float fcali = 55;
float bcali = 58;
float kp = 19/2;
float kd = 0.3/2;
float ki = 0.3/1.5;
float threshold = 10;
task main()
{
	float preverror = 0;
	float ierror = 0;
	while(true) {
		float f = (float)SensorValue(front);
		float b = (float)SensorValue(back);
		//writeDebugStreamLine("%d, %d", f, b);

		float error = f > fcali ? f-fcali : bcali - b;
		float derror = error - preverror;
		ierror = ierror + error;
		preverror = error;

		int sign1 = error > 0 ? 1 : -1;
		int sign2 = derror > 0 ? 1 : -1;
		int sign3 = ierror > 0 ? 1 : -1;
		//float pid = sign1 * kp * error * error + sign2 * kd * derror * derror + sign3 * ki * ierror * ierror;
		float pid = kp * error + kd * derror + ki * ierror;
		float power = pid;
		int sign = pid > 0 ? 1 : -1;
		power = abs(power) > 100 ? 80 * sign : power;
		writeDebugStreamLine("%d %d %d %d\n", error, derror, ierror, pid);
		//nxtDisplayTextLine(0,"%d\n", nImmediateBatteryLevel);
		//writeDebugStreamLine("%d\n", power);
		motor[leftMotor] = (int)power;
		motor[rightMotor] = (int)power;
		wait1Msec(5);
	}
	while(nNxtButtonPressed != kExitButton) {}
}
